In [3]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 15, 6

In [17]:
df = pd.read_csv('n26_v1.csv')
df.head()
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [5]:
df1=df.groupby('signup_date').count()

In [6]:
df2=df1['campaign']

In [11]:
df2.to_frame()

             campaign
signup_date
2017-01-01         67
2017-01-02         56
2017-01-03         47
2017-01-04         54
2017-01-05         50
2017-01-06         57
2017-01-07         54
2017-01-08         60
2017-01-09         59
2017-01-10         61
2017-01-11         52
2017-01-12         55
2017-01-13         56
2017-01-14         51
2017-01-15         61
2017-01-16         48
2017-01-17         51
2017-01-18         58
2017-01-19         58
2017-01-20         46
2017-01-21         54
2017-01-22         54
2017-01-23         45
2017-01-24         72
2017-01-25         54
2017-01-26         37
2017-01-27         56
2017-01-28         52
2017-01-29         46
2017-01-30         54
...               ...
2017-03-03         37
2017-03-04         54
2017-03-05         69
2017-03-06         50
2017-03-07         45
2017-03-08         42
2017-03-09         76
2017-03-10         59
2017-03-11         60
2017-03-12         52
2017-03-13         54
2017-03-14         69
2017-03-15         59
2017-03-16         54
2017-03-17         58
2017-03-18         57
2017-03-19         63
2017-03-20         52
2017-03-21         50
2017-03-22         58
2017-03-23         57
2017-03-24         49
2017-03-25         54
2017-03-26         71
2017-03-27         55
2017-03-28         38
2017-03-29         62
2017-03-30         60
2017-03-31         57
2017-04-01         55

[91 rows x 1 columns]

In [12]:
df.index

RangeIndex(start=0, stop=5000, step=1)

In [14]:
df.plot(df)

ValueError: Must pass DataFrame with boolean values only